steps:
  # Install dependencies.
  - name: 'node:lts'
    entrypoint: 'npm'
    args: [ 'ci' ]
  # Build website.
  - name: 'node:lts'
    entrypoint: 'npm'
    args: [ 'run' , 'build' ]
  # Upload to Google bucket setting headers.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gsutil'
    args: [
      '-m',
      'cp',
      '-c',
      '-z',
      'js,css,svg,eot,otf,ttf,html',
      '-r',
      '/workspace/build/*',
      'gs://$_DOMAIN_NAME'
    ]
  # Set cache values.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gsutil'
    args: [
      '-m',
      'setmeta',
      '-r',
      '-h',
      'cache-control: public, max-age=$_MAX_AGE',
      'gs://$_DOMAIN_NAME/*'
    ]
substitutions:
  _DOMAIN_NAME: 'docs.foundries.io'
  _MAX_AGE: '300'
